name: Release apkg binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -o apkg .
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./apkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
