name: Build and Release apkg

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

permissions:
  contents: write  # allow creating releases & uploading assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build static apkg binary
        run: |
          CGO_ENABLED=0 go build -ldflags="-s -w -extldflags '-static'" -o apkg .

      - name: Create release tarball
        run: |
          tar -cJf apkg-release.tar.xz apkg apkg.yaml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: apkg-release.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
