name: Build and Release apkg

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

permissions:
  contents: write  # allow creating releases & uploading assets

jobs:
  build:
    strategy:
      matrix:
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build static apkg binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
        run: |
          CGO_ENABLED=0 go build -ldflags="-s -w -extldflags '-static'" -o apkg .

      - name: Create release tarball
        run: |
          tar -cJf apkg-release-${{ matrix.goarch }}.tar.xz apkg apkg.yaml.template

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: apkg-release-${{ matrix.goarch }}
          path: apkg-release-${{ matrix.goarch }}.tar.xz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release-assets
          pattern: apkg-release-*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
